[project]
name = "jpretty"
description = "Playing with nicer display of JSON data"

readme = "README.rst"

authors = [
    {name = "Ned Batchelder", email = "ned@nedbatchelder.com"},
]

license.text = "Apache-2.0"

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

requires-python = ">= 3.11"

dependencies = [
    "rich",
]

dynamic = ["version"]

#[project.urls]
#"Source code" = "https://github.com/nedbat/jpretty"
#"Issue tracker" = "https://github.com/nedbat/jpretty/issues"

[project.scripts]
display_runs = "jpretty.display_runs:main"

[tool.setuptools.dynamic]
version.attr = "jpretty.__version__"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
